![imagen](../../imagenes/ejercicios.png)

## Ejercicio 1
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [4]:
import numpy as np 

zeros = np.zeros(10, dtype=int)
zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
zeros[3]= 1
zeros

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0])

## Ejercicio 2
Crea un vector que vaya del 10 al 49

Inviértelo

In [7]:
vector = np.arange(10,50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [9]:
np.flip(vector)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [10]:
vector[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## Ejericio 3
Encuentra los indices del vector [1,2,0,0,4,0], que no sean 0. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [132]:
v_1 = np.array([1,2,0,0,4,0])

mask = v_1 != 0

result = np.where(mask)
result

(array([0, 1, 4], dtype=int64),)

In [133]:
np.nonzero(v_1)

(array([0, 1, 4], dtype=int64),)

## Ejercicio 4
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [34]:
a_rand = np.random.randint(1, 1000, size = (1,10,10))
a_rand

array([[[325, 474, 112, 350, 678, 780, 615, 955, 680, 295],
        [225, 641, 492,  52, 383, 467, 350, 557, 593, 346],
        [693, 622, 148, 158, 879, 872, 627, 477, 549, 617],
        [341, 536, 361, 262, 988, 793, 930, 829, 922, 325],
        [ 27, 626, 458, 592, 656, 727, 388, 105,  50, 103],
        [527, 674, 446, 213, 110, 151, 853,   3, 150, 359],
        [ 62, 895, 128, 578, 518, 125, 464, 811, 778, 694],
        [227, 179, 272, 950, 925, 940, 366, 812, 554, 506],
        [612, 740,  95, 741, 281, 232,   3, 265, 837, 613],
        [716, 296, 828,  84, 379, 159,   9, 979, 189, 545]]])

In [35]:
np.max(a_rand), np.min(a_rand)

(988, 3)

In [37]:
a_rand[a_rand == np.min(a_rand)].size

2

In [38]:
a_rand[a_rand == np.max(a_rand)].size

1

## Ejercicio 5
Crea un vector aleatorio de tamaño 30 y calcula su media

In [44]:
v = np.random.randint(0,10,size=(1,30))
v

array([[4, 7, 6, 6, 6, 0, 3, 2, 2, 0, 8, 0, 7, 5, 7, 9, 3, 6, 8, 0, 8, 6,
        7, 6, 9, 6, 6, 2, 0, 6]])

In [46]:
np.average(v).round(2)

4.83

## Ejercicio 6
Crea un array cuadrado de 2D, con las dimensiones que quieas, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [69]:
bi_matrix = np.ones((2,4,4))
bi_matrix
bi_matrix[0,1:-1:,1:-1:] = 0
bi_matrix[1,1:-1:,1:-1:] = 0
bi_matrix

array([[[1., 1., 1., 1.],
        [1., 0., 0., 1.],
        [1., 0., 0., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 0., 0., 1.],
        [1., 0., 0., 1.],
        [1., 1., 1., 1.]]])

## Ejercicio 7
Crea una mtriz de 8x8, y rellenala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [149]:
vector = np.ones((8,8), dtype=int)

vector[::2,::2]= 0
vector[1::2,1::2]= 0

vector

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## Ejercicio 8
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [151]:
vector[:2,:2]

array([[0, 1],
       [1, 0]])

In [153]:
np.tile(vector[:2,:2],(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## Ejercicio 9
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [157]:
a = np.random.randint(1,20,(5,5))
a

array([[ 3,  2, 13, 14,  9],
       [ 5, 16, 18, 15,  6],
       [17,  7,  8, 17, 13],
       [18, 12,  2, 17, 17],
       [15,  9, 16, 17,  6]])

In [161]:
a = (a-np.mean(a))/np.std(a)
a

array([[-1.62712377, -1.81458043,  0.24744279,  0.43489944, -0.50238384],
       [-1.25221046,  0.80981275,  1.18472606,  0.6223561 , -1.0647538 ],
       [ 0.99726941, -0.87729715, -0.68984049,  0.99726941,  0.24744279],
       [ 1.18472606,  0.05998613, -1.81458043,  0.99726941,  0.99726941],
       [ 0.6223561 , -0.50238384,  0.80981275,  0.99726941, -1.0647538 ]])

## Ejercicio 10
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [168]:
x = np.arange(11)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [171]:
x[(x >= 3) & (x <= 8)] =-1
x

array([ 0,  1,  2, -1, -1, -1, -1, -1, -1,  9, 10])

In [176]:
[x == -1 ] 

[array([False, False, False,  True,  True,  True,  True,  True,  True,
        False, False])]