![imagen](../../imagenes/ejercicios.png)

## Ejercicio 1
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [1]:
import numpy as np

x = np.zeros(10)
print(x)
print("%d bytes" % (x.size * x.itemsize))
print(x.itemsize)
print(x.nbytes)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
80 bytes
8
80


In [ ]:
x[3] = 1
print(x)

## Ejercicio 2
Crea un vector que vaya del 10 al 49

Inviértelo

In [6]:
x = np.arange(10,50)
print(x)
print(x[::-1])

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejericio 3
Encuentra los indices del vector [1,2,0,0,4,0], que no sean 0. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [2]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [5]:
print(type(nz[0]))

<class 'numpy.ndarray'>


## Ejercicio 4
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [ ]:
x = np.random.random((10,10))
xmin, xmax = x.min(), x.max()
print(xmin, xmax)

## Ejercicio 5
Crea un vector aleatorio de tamaño 30 y calcula su media

In [8]:
x = np.random.random(30)
m = x.mean()
print(m)

0.49512311199600606


## Ejercicio 6
Crea un array cuadrado de 2D, con las dimensiones que quieas, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [9]:
x = np.ones((10,10))
x[1:-1, 1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## Ejercicio 7
Crea una mtriz de 8x8, y rellenala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [12]:
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 8
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [19]:
x = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 9
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [20]:
x = np.random.random((5,5))
x = (x - np.mean (x)) / (np.std (x))
print(x)

[[ 1.0284747  -0.84593325  1.35564882 -1.36963686 -0.49192254]
 [-1.43399394 -1.23935041  0.31265489  0.68070024  0.91751642]
 [ 1.60226319 -0.81577364 -0.60623586 -1.76482674  0.26815223]
 [-0.28472487 -0.36274955 -0.1583587   0.96475901  0.8627893 ]
 [ 0.10280535 -0.41276372  1.45406904 -1.15708657  1.39352346]]


## Ejercicio 10
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [26]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] = -1
print(Z)

[ 0  1  2  3 -1 -1 -1 -1 -1  9 10]


In [25]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]
