In [2]:
import numpy as np
print(np.arange(5))
print(np.arange(1, 6))

[0 1 2 3 4]
[1 2 3 4 5]


In [3]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [4]:
x = np.arange(5)
print(x)

y = np.zeros(10)
#np.power(2, x, out=y[::2])
print(y)

[0 1 2 3 4]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [ ]:
[1,2,4,8,16]

In [6]:
x = np.arange(1, 6)
print(x)

[1 2 3 4 5]


In [7]:
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [8]:
M = np.ones((3, 3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
a = np.array([0, 1, 2])
print(a)

[0 1 2]


In [10]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [11]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]

print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [12]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [13]:
M = np.ones((2, 3))
a = np.arange(3)
print(M)
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]


In [14]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.]])

In [15]:
X = np.random.random((10, 3))
print(X)

[[0.61399126 0.62224321 0.7133353 ]
 [0.00102892 0.48723087 0.12438637]
 [0.31895094 0.08657563 0.76024063]
 [0.62808752 0.05286394 0.01742049]
 [0.14612357 0.8320262  0.65759358]
 [0.48475142 0.87952681 0.73578053]
 [0.3656482  0.04463737 0.54324486]
 [0.94827162 0.5725861  0.0945856 ]
 [0.28755906 0.09457092 0.47426653]
 [0.58682797 0.15964238 0.61276609]]


In [16]:
Xmean = X.mean(0)
Xmean

array([0.43812405, 0.38319034, 0.473362  ])

In [18]:
X_centered = X - Xmean
print(X_centered)


[[ 0.17586722  0.23905287  0.2399733 ]
 [-0.43709513  0.10404053 -0.34897562]
 [-0.11917311 -0.29661471  0.28687863]
 [ 0.18996348 -0.33032641 -0.45594151]
 [-0.29200048  0.44883585  0.18423158]
 [ 0.04662737  0.49633646  0.26241853]
 [-0.07247585 -0.33855298  0.06988286]
 [ 0.51014757  0.18939576 -0.3787764 ]
 [-0.15056499 -0.28861942  0.00090453]
 [ 0.14870393 -0.22354796  0.13940409]]
