# Data Manipulation with Pandas

In the previous chapter, we dove into detail on NumPy and its ``ndarray`` object, which provides efficient storage and manipulation of dense typed arrays in Python.
Here we'll build on this knowledge by looking in detail at the data structures provided by the Pandas library.
Pandas is a newer package built on top of NumPy, and provides an efficient implementation of a ``DataFrame``.
``DataFrame``s are essentially multidimensional arrays with attached row and column labels, and often with heterogeneous types and/or missing data.
As well as offering a convenient storage interface for labeled data, Pandas implements a number of powerful data operations familiar to users of both database frameworks and spreadsheet programs.

As we saw, NumPy's ``ndarray`` data structure provides essential features for the type of clean, well-organized data typically seen in numerical computing tasks.
While it serves this purpose very well, its limitations become clear when we need more flexibility (e.g., attaching labels to data, working with missing data, etc.) and when attempting operations that do not map well to element-wise broadcasting (e.g., groupings, pivots, etc.), each of which is an important piece of analyzing the less structured data available in many forms in the world around us.
Pandas, and in particular its ``Series`` and ``DataFrame`` objects, builds on the NumPy array structure and provides efficient access to these sorts of "data munging" tasks that occupy much of a data scientist's time.

In this chapter, we will focus on the mechanics of using ``Series``, ``DataFrame``, and related structures effectively.
We will use examples drawn from real datasets where appropriate, but these examples are not necessarily the focus.

## Installing and Using Pandas

Installation of Pandas on your system requires NumPy to be installed, and if building the library from source, requires the appropriate tools to compile the C and Cython sources on which Pandas is built.
Details on this installation can be found in the [Pandas documentation](http://pandas.pydata.org/).
If you followed the advice outlined in the [Preface](00.00-Preface.ipynb) and used the Anaconda stack, you already have Pandas installed.

Once Pandas is installed, you can import it and check the version:

In [5]:
import pandas as pd 
import numpy as np 

In [3]:
pd.__version__

'0.25.1'

Just as we generally import NumPy under the alias ``np``, we will import Pandas under the alias ``pd``:

In [4]:
!pip freeze

alabaster==0.7.12
anaconda-client==1.7.2
anaconda-navigator==1.9.7
anaconda-project==0.8.3
asn1crypto==1.0.1
astroid==2.3.1
astropy==3.2.1
atomicwrites==1.3.0
attrs==19.2.0
Babel==2.7.0
backcall==0.1.0
backports.functools-lru-cache==1.6.1
backports.os==0.1.1
backports.shutil-get-terminal-size==1.0.0
backports.tempfile==1.0
backports.weakref==1.0.post1
beautifulsoup4==4.8.0
bitarray==1.0.1
bkcharts==0.2
bleach==3.1.0
bokeh==1.3.4
boto==2.49.0
Bottleneck==1.2.1
certifi==2019.9.11
cffi==1.12.3
chardet==3.0.4
Click==7.0
cloudpickle==1.2.2
clyent==1.2.2
colorama==0.4.1
comtypes==1.1.7
conda==4.8.3
conda-build==3.18.9
conda-package-handling==1.7.0
conda-verify==3.4.2
contextlib2==0.6.0
cryptography==2.7
cvxopt==1.2.4
cycler==0.10.0
Cython==0.29.13
cytoolz==0.10.0
dask==2.5.2
decorator==4.4.0
defusedxml==0.6.0
distributed==2.5.2
docutils==0.15.2
entrypoints==0.3
et-xmlfile==1.0.1
fastcache==1.1.0
filelock==3.0.12
Flask==1.1.1
fsspec==0.5.2
future==0.18.2
gevent==1.4.0
glob2==0.7
greenlet==0.4

This import convention will be used throughout the remainder of this book.

## Reminder about Built-In Documentation

As you read through this chapter, don't forget that IPython gives you the ability to quickly explore the contents of a package (by using the tab-completion feature) as well as the documentation of various functions (using the ``?`` character). (Refer back to [Help and Documentation in IPython](01.01-Help-And-Documentation.ipynb) if you need a refresher on this.)

For example, to display all the contents of the pandas namespace, you can type

```ipython
In [3]: pd.<TAB>
```

And to display Pandas's built-in documentation, you can use this:

```ipython
In [4]: pd?
```

More detailed documentation, along with tutorials and other resources, can be found at http://pandas.pydata.org/.

In [8]:
pd?

Type:        module
String form: <module 'pandas' from 'C:\\Users\\pilar\\Anaconda3\\lib\\site-packages\\pandas\\__init__.py'>
File:        c:\users\pilar\anaconda3\lib\site-packages\pandas\__init__.py
Docstring:  
pandas - a powerful data analysis and manipulation library for Python

**pandas** is a Python package providing fast, flexible, and expressive data
structures designed to make working with "relational" or "labeled" data both
easy and intuitive. It aims to be the fundamental high-level building block for
doing practical, **real world** data analysis in Python. Additionally, it has
the broader goal of becoming **the most powerful and flexible open source data
analysis / manipulation tool available in any language**. It is already well on
its way toward this goal.

Main Features
-------------
Here are just a few of the things that pandas does well:

  - Easy handling of missing data in floating point as well as non-floating
    point data.
  - Size mutability: columns can be in

In [9]:
help(pd)

Help on package pandas:

NAME
    pandas

DESCRIPTION
    pandas - a powerful data analysis and manipulation library for Python
    
    **pandas** is a Python package providing fast, flexible, and expressive data
    structures designed to make working with "relational" or "labeled" data both
    easy and intuitive. It aims to be the fundamental high-level building block for
    doing practical, **real world** data analysis in Python. Additionally, it has
    the broader goal of becoming **the most powerful and flexible open source data
    analysis / manipulation tool available in any language**. It is already well on
    its way toward this goal.
    
    Main Features
    -------------
    Here are just a few of the things that pandas does well:
    
      - Easy handling of missing data in floating point as well as non-floating
        point data.
      - Size mutability: columns can be inserted and deleted from DataFrame and
        higher dimensional objects
      - Automatic an

# Introducing Pandas Objects

At the very basic level, Pandas objects can be thought of as enhanced versions of NumPy structured arrays in which the rows and columns are identified with labels rather than simple integer indices.
As we will see during the course of this chapter, Pandas provides a host of useful tools, methods, and functionality on top of the basic data structures, but nearly everything that follows will require an understanding of what these structures are.
Thus, before we go any further, let's introduce these three fundamental Pandas data structures: the ``Series``, ``DataFrame``, and ``Index``.

We will start our code sessions with the standard NumPy and Pandas imports:

## The Pandas Series Object

A Pandas ``Series`` is a one-dimensional array of indexed data.
It can be created from a list or array as follows:

In [11]:
#Serie
data = pd.Series([0.25,0.50,0.75,1.])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [13]:
data.dtype

dtype('float64')

In [16]:
type(data)

pandas.core.series.Series

In [17]:
type(data.dtype)

numpy.dtype

As we see in the output, the ``Series`` wraps both a sequence of values and a sequence of indices, which we can access with the ``values`` and ``index`` attributes.
The ``values`` are simply a familiar NumPy array:

In [18]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [19]:
type(data.values)

numpy.ndarray

The ``index`` is an array-like object of type ``pd.Index``, which we'll discuss in more detail momentarily.

In [22]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [26]:
type(data.index)

pandas.core.indexes.range.RangeIndex

Like with a NumPy array, data can be accessed by the associated index via the familiar Python square-bracket notation:

In [28]:
data[2]

0.75

In [29]:
data.values[2]

0.75

In [33]:
data[1:] #Es una serie

1    0.50
2    0.75
3    1.00
dtype: float64

In [34]:
data.values[1:3] #Es un array

array([0.5 , 0.75])

As we will see, though, the Pandas ``Series`` is much more general and flexible than the one-dimensional NumPy array that it emulates.

### ``Series`` as generalized NumPy array

From what we've seen so far, it may look like the ``Series`` object is basically interchangeable with a one-dimensional NumPy array.
The essential difference is the presence of the index: while the Numpy Array has an *implicitly defined* integer index used to access the values, the Pandas ``Series`` has an *explicitly defined* index associated with the values.

This explicit index definition gives the ``Series`` object additional capabilities. For example, the index need not be an integer, but can consist of values of any desired type.
For example, if we wish, we can use strings as an index:

In [37]:
data = pd.Series([0.25,0.50,0.75,1.], index=["a","b","c","d"])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

And the item access works as expected:

In [40]:
data.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [42]:
data["c"]

0.75

We can even use non-contiguous or non-sequential indices:

In [43]:
data = pd.Series([0.25,0.50,0.75,1.], index=([2,5,3,9]))
data

2    0.25
5    0.50
3    0.75
9    1.00
dtype: float64

In [44]:
data[5]

0.5

In [ ]:
data = pd.Series((0.25,0.50,0.75,1.), index=([2,5,3,9])) #Lo declaramos con una tupla en vez de lista
data #Los '.values' siguen siendo un numpyArray

In [45]:
#Cuidado con las dimensiones
data = pd.Series((0.25,0.50,0.75,1.), index=([2,5,3,9,6]))
data

ValueError: Length of passed values is 4, index implies 5

### Series as specialized dictionary

In this way, you can think of a Pandas ``Series`` a bit like a specialization of a Python dictionary.
A dictionary is a structure that maps arbitrary keys to a set of arbitrary values, and a ``Series`` is a structure which maps typed keys to a set of typed values.
This typing is important: just as the type-specific compiled code behind a NumPy array makes it more efficient than a Python list for certain operations, the type information of a Pandas ``Series`` makes it much more efficient than Python dictionaries for certain operations.

The ``Series``-as-dictionary analogy can be made even more clear by constructing a ``Series`` object directly from a Python dictionary:

In [50]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population_dict

{'California': 38332521,
 'Texas': 26448193,
 'New York': 19651127,
 'Florida': 19552860,
 'Illinois': 12882135}

In [52]:
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [55]:
population.values  

array([38332521, 26448193, 19651127, 19552860, 12882135], dtype=int64)

In [57]:
population.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [59]:
print(population.index.values)
print(type(population.index.values))

['California' 'Texas' 'New York' 'Florida' 'Illinois']
<class 'numpy.ndarray'>


By default, a ``Series`` will be created where the index is drawn from the sorted keys.
From here, typical dictionary-style item access can be performed:

In [63]:
population['California']

38332521

Unlike a dictionary, though, the ``Series`` also supports array-style operations such as slicing:

In [64]:
population["California":"Florida"]

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
dtype: int64

We'll discuss some of the quirks of Pandas indexing and slicing in [Data Indexing and Selection](03.02-Data-Indexing-and-Selection.ipynb).

### Constructing Series objects

We've already seen a few ways of constructing a Pandas ``Series`` from scratch; all of them are some version of the following:

```python
>>> pd.Series(data, index=index)
```

where ``index`` is an optional argument, and ``data`` can be one of many entities.

For example, ``data`` can be a list or NumPy array, in which case ``index`` defaults to an integer sequence:

In [66]:
pd.Series([2,3,4])

0    2
1    3
2    4
dtype: int64

In [70]:
datos = [2,3,4]
pd.Series(datos, index = range(1,len(datos)+1))

1    2
2    3
3    4
dtype: int64

``data`` can be a scalar, which is repeated to fill the specified index:

In [72]:
prueba = pd.Series(5, index = [1,2,3])
prueba

1    5
2    5
3    5
dtype: int64

In [73]:
prueba[2]

5

``data`` can be a dictionary, in which ``index`` defaults to the sorted dictionary keys:

In [74]:
pd.Series({2:"a",1:"b",3:"c",5:"d",4:"e"})

2    a
1    b
3    c
5    d
4    e
dtype: object

In each case, the index can be explicitly set if a different result is preferred:

In [76]:
pd.Series({2:"a",1:"b",3:"c",5:"d",4:"e"}, index=[1,2,3,4,5])

1    b
2    a
3    c
4    e
5    d
dtype: object

In [78]:
pd.Series({2:"a",1:"b",3:"c",5:"d",4:"e"}, index=[1,2,5]) #podemos filtra cuando se crea la serie

1    b
2    a
5    d
dtype: object

Notice that in this case, the ``Series`` is populated only with the explicitly identified keys.

## The Pandas DataFrame Object

The next fundamental structure in Pandas is the ``DataFrame``.
Like the ``Series`` object discussed in the previous section, the ``DataFrame`` can be thought of either as a generalization of a NumPy array, or as a specialization of a Python dictionary.
We'll now take a look at each of these perspectives.

### DataFrame as a generalized NumPy array
If a ``Series`` is an analog of a one-dimensional array with flexible indices, a ``DataFrame`` is an analog of a two-dimensional array with both flexible row indices and flexible column names.
Just as you might think of a two-dimensional array as an ordered sequence of aligned one-dimensional columns, you can think of a ``DataFrame`` as a sequence of aligned ``Series`` objects.
Here, by "aligned" we mean that they share the same index.

To demonstrate this, let's first construct a new ``Series`` listing the area of each of the five states discussed in the previous section:

In [95]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area_dict

{'California': 423967,
 'Texas': 695662,
 'New York': 141297,
 'Florida': 170312,
 'Illinois': 149995}

In [81]:
areas = pd.Series(area_dict)
areas

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

Now that we have this along with the ``population`` Series from before, we can use a dictionary to construct a single two-dimensional object containing this information:

In [82]:
#Crear un DataFrame
states = pd.DataFrame({"Poblacion":population,"Area":areas})
states

Poblacion    Area
California   38332521  423967
Texas        26448193  695662
New York     19651127  141297
Florida      19552860  170312
Illinois     12882135  149995

Like the ``Series`` object, the ``DataFrame`` has an ``index`` attribute that gives access to the index labels:

In [84]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [86]:
states.values

array([[38332521,   423967],
       [26448193,   695662],
       [19651127,   141297],
       [19552860,   170312],
       [12882135,   149995]], dtype=int64)

Additionally, the ``DataFrame`` has a ``columns`` attribute, which is an ``Index`` object holding the column labels:

In [89]:
states.columns

Index(['Poblacion', 'Area'], dtype='object')

In [91]:
states.columns.values

array(['Poblacion', 'Area'], dtype=object)

In [93]:
states.values.shape

(5, 2)

Thus the ``DataFrame`` can be thought of as a generalization of a two-dimensional NumPy array, where both the rows and columns have a generalized index for accessing the data.

In [97]:
area_dict2 = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312}
areas2 = pd.Series(area_dict2)
states2 = pd.DataFrame({"Poblacion": population, "Area":areas2})
states2

Poblacion      Area
California   38332521  423967.0
Florida      19552860  170312.0
Illinois     12882135       NaN
New York     19651127  141297.0
Texas        26448193  695662.0

In [101]:
print(states['Area'])
print(type(states['Area'])) #Series

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: Area, dtype: int64
<class 'pandas.core.series.Series'>


In [105]:
print(states['Area']['Illinois']) #Siempre primero columna en 
print(states['Area'][4]) #Indice interno

149995
149995


In [ ]:
states['Area']['Illinois']

### DataFrame as specialized dictionary

Similarly, we can also think of a ``DataFrame`` as a specialization of a dictionary.
Where a dictionary maps a key to a value, a ``DataFrame`` maps a column name to a ``Series`` of column data.
For example, asking for the ``'area'`` attribute returns the ``Series`` object containing the areas we saw earlier:

In [108]:
states['Poblacion']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: Poblacion, dtype: int64

In [109]:
states.Poblacion

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: Poblacion, dtype: int64

In [112]:
print(type(states.loc['California']))
states.loc['California']

<class 'pandas.core.series.Series'>


Poblacion    38332521
Area           423967
Name: California, dtype: int64

Notice the potential point of confusion here: in a two-dimesnional NumPy array, ``data[0]`` will return the first *row*. For a ``DataFrame``, ``data['col0']`` will return the first *column*.
Because of this, it is probably better to think about ``DataFrame``s as generalized dictionaries rather than generalized arrays, though both ways of looking at the situation can be useful.
We'll explore more flexible means of indexing ``DataFrame``s in [Data Indexing and Selection](03.02-Data-Indexing-and-Selection.ipynb).

### Constructing DataFrame objects

A Pandas ``DataFrame`` can be constructed in a variety of ways.
Here we'll give several examples.

#### From a single Series object

A ``DataFrame`` is a collection of ``Series`` objects, and a single-column ``DataFrame`` can be constructed from a single ``Series``:

In [113]:
pd.DataFrame(population)

0
California  38332521
Texas       26448193
New York    19651127
Florida     19552860
Illinois    12882135

In [116]:
pd.DataFrame(population, columns=['Population'])

Population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

In [119]:
population_dict

{'California': 38332521,
 'Texas': 26448193,
 'New York': 19651127,
 'Florida': 19552860,
 'Illinois': 12882135}

In [121]:
pd.DataFrame(population_dict, index = [1,2])

California     Texas  New York   Florida  Illinois
1    38332521  26448193  19651127  19552860  12882135
2    38332521  26448193  19651127  19552860  12882135

#### From a list of dicts

Any list of dictionaries can be made into a ``DataFrame``.
We'll use a simple list comprehension to create some data:

In [122]:
df = pd.DataFrame({"Population":[1,2,3,4],"Area":(5,6,7,8)})
print(df)
print(type(df))
print(type(df.Population))

Population  Area
0           1     5
1           2     6
2           3     7
3           4     8
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


Even if some keys in the dictionary are missing, Pandas will fill them in with ``NaN`` (i.e., "not a number") values:

In [123]:
pd.DataFrame([{"a":1,"b":2},
                {"c":5,"b":4}])

a  b    c
0  1.0  2  NaN
1  NaN  4  5.0

#### From a dictionary of Series objects

As we saw before, a ``DataFrame`` can be constructed from a dictionary of ``Series`` objects as well:

In [124]:
states

Poblacion    Area
California   38332521  423967
Texas        26448193  695662
New York     19651127  141297
Florida      19552860  170312
Illinois     12882135  149995

#### From a two-dimensional NumPy array

Given a two-dimensional array of data, we can create a ``DataFrame`` with any specified column and index names.
If omitted, an integer index will be used for each:

In [126]:
np.random.rand(3,2)

array([[0.28374028, 0.63493519],
       [0.69868662, 0.73490933],
       [0.23868114, 0.20199038]])

In [128]:
pd.DataFrame(np.random.rand(3,2),columns=["a","b"], index=["x","y","z"])

a         b
x  0.880314  0.376320
y  0.507364  0.323837
z  0.520624  0.518494

#### From a NumPy structured array

We covered structured arrays in [Structured Data: NumPy's Structured Arrays](02.09-Structured-Data-NumPy.ipynb).
A Pandas ``DataFrame`` operates much like a structured array, and can be created directly from one:

In [132]:
A = np.zeros((3,2))
A

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [133]:
pd.DataFrame(A,columns=["a","b"], index=["x","y","z"])

a    b
x  0.0  0.0
y  0.0  0.0
z  0.0  0.0

## The Pandas Index Object

We have seen here that both the ``Series`` and ``DataFrame`` objects contain an explicit *index* that lets you reference and modify data.
This ``Index`` object is an interesting structure in itself, and it can be thought of either as an *immutable array* or as an *ordered set* (technically a multi-set, as ``Index`` objects may contain repeated values).
Those views have some interesting consequences in the operations available on ``Index`` objects.
As a simple example, let's construct an ``Index`` from a list of integers:

In [136]:
ind = pd.Index([2,4,6,8,10]) #Indice es inmutable
print(type(ind))
ind

<class 'pandas.core.indexes.numeric.Int64Index'>


Int64Index([2, 4, 6, 8, 10], dtype='int64')

### Index as immutable array

The ``Index`` in many ways operates like an array.
For example, we can use standard Python indexing notation to retrieve values or slices:

In [140]:
ind[3]

8

In [141]:
ind[::2]


Int64Index([2, 6, 10], dtype='int64')

``Index`` objects also have many of the attributes familiar from NumPy arrays:

In [143]:
print("Size:",ind.size)
print("Shape:", ind.shape)
print("nDim:", ind.ndim)
print("dtype:", ind.dtype)

Size: 5
Shape: (5,)
nDim: 1
dtype: int64


One difference between ``Index`` objects and NumPy arrays is that indices are immutable–that is, they cannot be modified via the normal means:

In [144]:
ind[2]= 100

TypeError: Index does not support mutable operations

This immutability makes it safer to share indices between multiple ``DataFrame``s and arrays, without the potential for side effects from inadvertent index modification.

### Index as ordered set

Pandas objects are designed to facilitate operations such as joins across datasets, which depend on many aspects of set arithmetic.
The ``Index`` object follows many of the conventions used by Python's built-in ``set`` data structure, so that unions, intersections, differences, and other combinations can be computed in a familiar way:

In [145]:
indA = pd.Index([1,3,5,7,9])
indB = pd.Index([2,3,4,5,6])

In [147]:
#Intersección
indA & indB

Int64Index([3, 5], dtype='int64')

In [148]:
#Unión
indA | indB

Int64Index([1, 2, 3, 4, 5, 6, 7, 9], dtype='int64')

These operations may also be accessed via object methods, for example ``indA.intersection(indB)``.